title: ShenTech
email: info@shentech.com
description: ''
baseurl: ''
url: buner
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
